### ISSUE TITLE
Booking Roadmap

### ISSUE THREAD

**Issue by N0ah-S** [Gold-Squadron/XY-Fleet#68]
- [ ] #38
- [ ] visualize different booking types/stati
- [ ] add proper autocomplete to drivers
- [ ] add proper autocomplete to cars
- [ ] add *preview* option
- [ ] ask user whether he wants to restore the input of the last cancelled mask
